version = 1

[[analyzers]]  
name = "javascript"  

[analyzers.meta]
  plugins = ["react"]
  environment = ["mongo", "jquery"]
  module_system = "es-modules"
  dialect = "flow"
  skip_doc_coverage = ["class-expression", "method-definition"]

enabled = true
