import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import { Product } from "../components/Product";
import { Gallery } from "../styles/Gallery";

export default function Home() {
  const [result] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = result;
  if (fetching) return <p>Loading ...</p>;
  if (error) return <p>Error ...</p>;

  const products = data.products.data;
  console.log(products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Gallery>
          {products.map((product) => {
            return <Product key={product.attributes.slug} product={product} />;
          })}
        </Gallery>
      </main>
    </div>
  );
}
